version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rentafacil-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Passw0rd12345!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  vehicle-service:
    build:
      context: ./src/VehicleService
      dockerfile: Dockerfile
    container_name: rentafacil-vehicle
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=RentaFacilVehicleDb;User Id=sa;Password=Passw0rd12345!;TrustServerCertificate=True;Encrypt=False;"
    ports:
      - "5201:8080"
    depends_on:
      - sqlserver

  booking-service:
    build:
      context: ./src/BookingService
      dockerfile: Dockerfile
    container_name: rentafacil-booking
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=RentaFacilBookingDb;User Id=sa;Password=Passw0rd12345!;TrustServerCertificate=True;Encrypt=False;"
      VehicleService__BaseUrl: "http://vehicle-service:8080"
    ports:
      - "5202:8080"
    depends_on:
      - sqlserver
      - vehicle-service

  report-worker:
    build:
      context: ./src/ReportWorker
      dockerfile: Dockerfile
    container_name: rentafacil-report-worker
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=RentaFacilReportDb;User Id=sa;Password=Passw0rd12345!;TrustServerCertificate=True;Encrypt=False;"
    depends_on:
      - sqlserver

volumes:
  sqlserver_data:
